# Generated by Django 5.0 on 2023-12-23 14:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("user_data", "0010_client_next_meeting_date"),
        ("whatsapp_instance", "0002_delete_clients"),
    ]

    operations = [
        migrations.CreateModel(
            name="ClientMessage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("message", models.TextField()),
                ("date", models.DateTimeField(auto_now_add=True)),
                (
                    "client",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="user_data.client",
                    ),
                ),
            ],
        ),
    ]
