# Generated by Django 5.0 on 2023-12-23 11:10

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("user_data", "0003_alter_user_created_at_alter_user_email_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="phone",
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
