# Generated by Django 5.0 on 2023-12-23 11:17

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("user_data", "0004_alter_user_phone"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="is_staff",
            field=models.BooleanField(default=False),
        ),
    ]
