# Generated by Django 5.0 on 2023-12-23 13:00

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("user_data", "0006_user_groups_user_user_permissions"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="company",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to="user_data.company",
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="company",
            name="created_at",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
