# Generated by Django 5.0 on 2023-12-23 13:56

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("user_data", "0008_clients"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Clients",
            new_name="Client",
        ),
    ]
