# Generated by Django 5.0 on 2023-12-23 14:34

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("user_data", "0009_rename_clients_client"),
    ]

    operations = [
        migrations.AddField(
            model_name="client",
            name="next_meeting_date",
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
    ]
