# Generated by Django 5.0 on 2023-12-23 17:20

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("user_data", "0010_client_next_meeting_date"),
    ]

    operations = [
        migrations.AddField(
            model_name="client",
            name="message",
            field=models.TextField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name="company",
            name="email",
            field=models.CharField(blank=True, default=None, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name="company",
            name="phone",
            field=models.CharField(blank=True, default=None, max_length=50, null=True),
        ),
    ]
