# Generated by Django 5.0 on 2023-12-23 17:33

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("user_data", "0011_client_message_company_email_company_phone"),
    ]

    operations = [
        migrations.RenameField(
            model_name="client",
            old_name="phone",
            new_name="phone_number",
        ),
    ]
