# Generated by Django 5.0 on 2023-12-23 18:50

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("user_data", "0012_rename_phone_client_phone_number"),
    ]

    operations = [
        migrations.RenameField(
            model_name="user",
            old_name="phone",
            new_name="phone_number",
        ),
        migrations.RemoveField(
            model_name="company",
            name="created_at",
        ),
        migrations.RemoveField(
            model_name="company",
            name="email",
        ),
        migrations.RemoveField(
            model_name="company",
            name="phone",
        ),
    ]
